<?php

namespace AppBundle\Repository;

/**
 * ComentarioEquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioEquipoRepository extends \Doctrine\ORM\EntityRepository
{
}
